removed more name clashes by blacklisting. error remains:
CAMLOPT -pp -c -for-pack Demo_plugin src/g_demo_plugin.ml4
File "_none_", line 1:
Error: Unbound module Run_extractable