fixed many compilation errors. 1 remains:
File "src/denote.ml", line 1:
Error: The implementation src/denote.ml
       does not match the interface src/denote.cmi:
       The value `denote_term' is required but not provided